# Generated by Django 3.0.2 on 2020-03-09 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryposts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('category', models.CharField(default='Technology', max_length=50)),
                ('desc', models.TextField()),
                ('about', models.TextField(default='About Company')),
                ('eligibility', models.TextField(default='Eligibility criteria of company')),
                ('skills', models.TextField(default='skills required')),
                ('questions', models.TextField(default='frequently asked questions in the interview')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comments_count', models.IntegerField()),
                ('homepost', models.BooleanField(default=False)),
                ('blogpost', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='one.Categoryposts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
