# Generated by Django 3.0.2 on 2020-03-25 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_auto_20200325_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
