# Generated by Django 3.0.2 on 2020-03-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_auto_20200325_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='explain_rounds',
            new_name='interview_Experience',
        ),
        migrations.AddField(
            model_name='interview',
            name='selected_year',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='interview',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
