# Generated by Django 3.0.2 on 2020-03-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_auto_20200325_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='package',
            field=models.CharField(default='', max_length=100),
        ),
    ]
