# Generated by Django 3.0.2 on 2020-03-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0006_auto_20200325_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='select',
            field=models.BooleanField(default=True),
        ),
    ]
